version: "3.9"

volumes:
  sns_postgres_data:

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: sns_frontend_container
    tty: true
    volumes:
      - .:/app
      # - node_modules:/app/frontend/node_modules
    ports:
      - 5173:5173
    command: yarn dev

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: sns_backend_container
    ports:
      - 3001:3000
    tty: true
    volumes:
      - .:/app
    depends_on:
      - db
    command: yarn start

  db:
    image: postgres:15
    container_name: sns_postgres-db
    volumes:
      - sns_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
